---
all:
  children:
    tower:
      hosts:
        tower01:
        tower02:
        tower03:
    automationhub:
      hosts:
        hub:
    isolated_group_restrictedzone:
      hosts:
        isolated:
    database:
      hosts:
        pgsql:
